<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="keml" nsURI="http://www.unikoblenz.de/keml" nsPrefix="keml">
  <eClassifiers xsi:type="ecore:EClass" name="Conversation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" lowerBound="1"
        eType="#//Author" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conversationPartners" upperBound="-1"
        eType="#//ConversationPartner" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConversationPartner" eSuperTypes="#//LifeLine">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Conversation partners are for example the LLM and a web browser, more or less are possible"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LifeLine" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="LifeLines are defined by the UML standard as essential parts of a sequence diagram.&#xA;The xPosition positions the life line on the horizontal axis. Vertically, it starts as high as possible."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Author" eSuperTypes="#//LifeLine">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The human main author of the conversation"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
        eType="#//Message" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preknowledge" upperBound="-1"
        eType="#//PreKnowledge" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SendMessage" eSuperTypes="#//Message">
    <eStructuralFeatures xsi:type="ecore:EReference" name="uses" upperBound="-1" eType="#//Information"
        eOpposite="#//Information/isUsedOn"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReceiveMessage" eSuperTypes="#//Message">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInterrupted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generates" upperBound="-1"
        eType="#//NewInformation" containment="true" eOpposite="#//NewInformation/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repeats" upperBound="-1"
        eType="#//Information" eOpposite="#//Information/repeatedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="counterPart" lowerBound="1"
        eType="#//ConversationPartner"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originalContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewInformation" eSuperTypes="#//Information">
    <eOperations name="getSourceConversationPartner" eType="#//ConversationPartner"/>
    <eOperations name="getTiming" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ReceiveMessage" eOpposite="#//ReceiveMessage/generates"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreKnowledge" eSuperTypes="#//Information"/>
  <eClassifiers xsi:type="ecore:EClass" name="Information" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInstruction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repeatedBy" upperBound="-1"
        eType="#//ReceiveMessage" eOpposite="#//ReceiveMessage/repeats"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetedBy" upperBound="-1"
        eType="#//InformationLink" eOpposite="#//InformationLink/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="causes" upperBound="-1"
        eType="#//InformationLink" containment="true" eOpposite="#//InformationLink/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isUsedOn" upperBound="-1"
        eType="#//SendMessage" eOpposite="#//SendMessage/uses"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="feltTrustImmediately" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="feltTrustAfterwards" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialTrust" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentTrust" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InformationLinkType">
    <eLiterals name="SUPPLEMENT"/>
    <eLiterals name="SUPPORT" value="1"/>
    <eLiterals name="STRONG_SUPPORT" value="2" literal="STRONG_SUPPORT"/>
    <eLiterals name="ATTACK" value="3" literal="ATTACK"/>
    <eLiterals name="STRONG_ATTACK" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InformationLink">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//InformationLinkType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Information" eOpposite="#//Information/targetedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Information" eOpposite="#//Information/causes"/>
  </eClassifiers>
</ecore:EPackage>
